-   id: check-branch-linearity
    name: Check for git branch linearity
    language: script
    entry: ./git-branch-linearity.sh
    always_run: true
    pass_filenames: false
    stages: [push]

-   id: check-branch-name
    name: Check branch name
    language: script
    entry: ./branch-naming.sh
    always_run: true
    pass_filenames: false
    stages: [push]

-   id: no-ephemeral-links
    name: No ephemeral links
    language: script
    entry: ./no-ephemeral-links.sh
    stages: [commit]

-   id: fastapi-generate-openapi-specification
    name: Generate Open API specification from a Fast API
    language: script
    entry: ./fastapi-generate-openapi-specification.sh
    stages: [commit]
    pass_filenames: false

-   id: gitops-values-validation
    name: GitOps values JSON schema validation
    language: python
    entry: python -m kp_pre_commit_hooks.gitops-values-validation
    stages: [commit]
    always_run: true
    pass_filenames: false

-   id: kafka-check-schemas
    name: Check if local Kafka Schemas are up to date with code
    language: script
    entry: ./kafka-check-local-schemas.sh
    stages: [commit]
    files: ^(schemas/|src/main/scala/[^/]+/models/)
    pass_filenames: false
