-   id: check-branch-linearity
    name: Check for git branch linearity
    language: script
    entry: ./git-branch-linearity.sh
    always_run: true
    pass_filenames: false
    stages: [push]

-   id: check-branch-name
    name: Check branch name
    language: script
    entry: ./branch-naming.sh
    always_run: true
    pass_filenames: false
    stages: [push]

-   id: no-ephemeral-links
    name: No ephemeral links
    language: script
    entry: ./no-ephemeral-links.sh
    stages: [commit]

-   id: generate-open-api-spec-from-fast-api
    name: Generate Open API specification from a Fast API
    language: system
    entry: poetry run python ./fast_api_generate_openapi_specification.py
    stages: [commit]
