-   id: check-branch-linearity
    name: Check for git branch linearity
    language: script
    entry: ./git-branch-linearity.sh
    always_run: true
    pass_filenames: false
    stages: [push]

-   id: check-branch-name
    name: Check branch name
    language: script
    entry: ./branch-naming.sh
    always_run: true
    pass_filenames: false
    stages: [push]

-   id: check-commit-first-line-length
    name: Check commit first line length
    language: script
    entry: ./check-commit-msg-length.sh
    always_run: true
    pass_filenames: false
    stages: [push]
-   id: no-ephemeral-links
    name: No ephemeral links
    language: script
    entry: ./no-ephemeral-links.sh
    stages: [commit]
