repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        # Override default [push, commit]
        stages: [commit]
    -   id: trailing-whitespace
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: ad1b27d73581aa16cca06fc4a0761fc563ffe8e8 # v1.5.6
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
