-   id: check-branch-linearity
    name: Check for git branch linearity
    language: script
    entry: ./git-branch-linearity.sh
    always_run: true
    pass_filenames: false
    stages: [push]

-   id: check-branch-name
    name: Check branch name
    language: script
    entry: ./branch-naming.sh
    always_run: true
    pass_filenames: false
    stages: [push]
