-   id: check-branch-linearity
    name: Check for git branch linearity
    language: script
    entry: ./git-branch-linearity.sh
    always_run: true
    pass_filenames: false
    stages: [push]

-   id: check-branch-name
    name: Check branch name
    language: script
    entry: ./branch-naming.sh
    always_run: true
    pass_filenames: false
    stages: [push]

-   id: no-ephemeral-links
    name: No ephemeral links
    language: script
    entry: ./no-ephemeral-links.sh
    stages: [commit]

-   id: fastapi-generate-openapi-specification
    name: Generate Open API specification from a Fast API
    language: script
    entry: ./fastapi-generate-openapi-specification.sh
    stages: [commit]
    pass_filenames: false

-   id: values-jsonschema-validation
    name: Jsonschema validation
    language: python
    entry: python ./chart-values-json-schema-validation.py
    stages: [commit]
