repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        # Override default [push, commit]
        stages: [commit]
    -   id: trailing-whitespace
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: a30f0d816e5062a67d87c8de753cfe499672b959 # v1.5.5
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
