name: 'Pre-commit'
description: 'Run pre-commit hooks'
inputs:
  skipped-hooks:
    description: 'Skip some hooks, eg "no-commit-to-branch,foo"'
    required: true
    default: ''
  main-branch:
    description: 'master or main'
    required: true
    default: 'main'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7.9'
    - name: Skip some hooks
      run: echo "SKIP=${{ inputs.skipped-hooks }}" >> $GITHUB_ENV
      if: ${{ inputs.skipped-hooks }} != ''
      shell: bash
    - name: Install pre-commit
      run: pip install pre-commit
      shell: bash
    - name: Cache pre-commit hooks
      uses: actions/cache@v2
      with:
        path: '~/.cache/pre-commit'
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run pre-commit
      run: |
            pre-commit run --show-diff-on-failure --color=always --all-files --hook-stage commit
            pre-commit run --show-diff-on-failure --color=always --all-files --hook-stage push

            # https://github.com/jorisroovers/gitlint/issues/148
            git config --add user.email ''
            git config --add user.name ''

            git fetch origin ${{ inputs.main-branch }} 2> /dev/null
            for commit in $(git rev-list origin/${{ inputs.main-branch }}..HEAD)
            do
               git show -s --pretty=format:%B $commit > tmp
               pre-commit run --color=always --hook-stage commit-msg --commit-msg-filename tmp
            done
      shell: bash

