name: bump-version

on:
  push:
    branches:
      - main
    paths-ignore:
      - .pre-commit-config.yaml
      - shell.nix
      - README.md
      - .github/**

jobs:
  bump-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
