name: bump-version

on:
  push:
    branches:
      - main
    paths-ignore:
      - .pre-commit-config.yaml
      - shell.nix
      - README.md
      - .github/**

jobs:
  bump-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
        with:
          fetch-depth: '0'
      - uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8  # 1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
